# Generated by Django 5.1.4 on 2024-12-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Select the first day of the reporting month')),
                ('cash_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reliever_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airtime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_expense_reason', models.TextField(blank=True, null=True)),
                ('other_expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_banking', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jandee.branch')),
            ],
        ),
    ]
